### ISSUE TITLE
Export standalone hash / digest function (or switch to a 3rd party module)

### ISSUE THREAD

**Issue by shevron** [datopian/data.js#108]
Would be great if the hash / digest function could be used on any browser `File` / `Blob` object (e.g. the result of `File.slice()`) and not just specifically on frictionless File objects. This would be useful to me in ckan-client-js. 

Even better, I don't see why not to use a 3rd party module for hash calculations, and avoid implementing it ourselves all together. If this happens, I could just rely on the same 3rd party module in ckan-client-js.

**Comment by rufuspollock** [comment]
@risenW @kmanaseryan I thought we had a hash function here including hash256 (and using streaming approach). 

@shevron can you describe exactly the signature and function of the method(s) you want?

**Comment by risenW** [comment]
@rufuspollock Yes we have an internal compute hash function that accepts a stream and incrementally computes the hash (see function [here](https://github.com/frictionlessdata/frictionless-js/blob/363504b20de8eb954aaefffe868126d1a3abc367/src/file-base.js#L196)). 

@shevron have you tried using the internal [_computeHash](https://github.com/frictionlessdata/frictionless-js/blob/363504b20de8eb954aaefffe868126d1a3abc367/src/file-base.js#L196)? If it works for you, we can export it, because it is currently internal

**Comment by shevron** [comment]
@rufuspollock the one we have, `_computeHash`, is what I need. I just need it exported publicly. But as I said I'd rather just use a 3rd party module. I see no reason to reinvent the wheel here if such module exists.

**Comment by rufuspollock** [comment]
@risenW is there an existing 3rd party module or do we just want to export the internal function. Also, i thought there was supposed to be `hash` and `hash256` functions on the base `File`? Aren't those the public methods we want to use?

**Comment by risenW** [comment]
> @risenW is there an existing 3rd party module or do we just want to export the internal function. Also, I thought there was supposed to be `hash` and `hash256` functions on the base `File`? Aren't those the public methods we want to use?

I'll export the existing function now. As regards hash and hash256, we deprecated hash256, as we decided to use a single API (hash), so you can use different algorithm types passed as parameters. 

Update: see this pull https://github.com/frictionlessdata/frictionless-js/pull/110
