### ISSUE TITLE
TransformStream not supported outside of Chrome

### ISSUE THREAD

**Issue by acouch** [datopian/data.js#50]
[TransformStream](https://github.com/datopian/data.js/blob/master/lib/parser/csv.js#L15) does not look like it is supported outside of Chrome: https://www.chromestatus.com/feature/5466425791610880 . Maybe a pollyfil could be used until it is fully adopted? Looks like this is an option? https://github.com/MattiasBuelens/web-streams-polyfill

**Comment by rufuspollock** [comment]
@anuveyatsu i think we need to look at this and compare with table schema lib and how they do this.

**Comment by rufuspollock** [comment]
@anuveyatsu any thoughts on this? @mariorodeghiero could take a look or @kmanaseryan

**Comment by anuveyatsu** [comment]
@rufuspollock yes, I think we need to implement the polyfill to support browsers such as Edge and Safari. This lib was originally written for node.js but then we started using it in browsers but only considered Chrome back then.

**Comment by kmanaseryan** [comment]
@anuveyatsu I've checked the suggested pollyfill seems we can have that integrated, but first want to test this in the browser. Could you please let me know what's the easiest way to run this in the browser? Seems we have babel setup, but it doesn't compile to ES2015+ syntax.  

Related #65

**Comment by kmanaseryan** [comment]
OK, just integrated webpack and built the lib for the browser, but not sure if this enough? I've created a browser bundle which size is **2.4MB**

**Comment by anuveyatsu** [comment]
@kmanaseryan have you tried `yarn compile` as here https://github.com/datopian/data.js/blob/master/package.json#L13 ?

If it doesn't help, then I'd use webpack which should be enough.

**Comment by kmanaseryan** [comment]
Yup, as you can see I've also used webpack, but just letting you know that the bundle is too big.

**Comment by kmanaseryan** [comment]
So just to clarify the issue this is what you get in the Safari browser:

`ReferenceError: Can't find variable: TransformStream ...`

**Comment by rufuspollock** [comment]
@kmanaseryan where are we using TransformStream from? Perhaps it is a code path we don't need for datapub ...

**Comment by kmanaseryan** [comment]
> @kmanaseryan where are we using TransformStream from? Perhaps it is a code path we don't need for datapub ...

@rufuspollock [here](https://github.com/datopian/data.js/blob/master/src/index.js#L189)

**Comment by kmanaseryan** [comment]
OK, after integrating the polyfill, I get the following error in Chrome:

`TypeError: Failed to execute 'pipeThrough' on 'ReadableStream': parameter 1's 'writable' property is not a WritableStream.`

In Safar:

`Unhandled Promise Rejection: TypeError: |this| is not a Promise`

**Comment by rufuspollock** [comment]
@kmanaseryan some small feedback:

> @rufuspollock here

You want to excerpt the section if you can or give some context. Why? Because i get emails of your comments and i would be able to give immediate feedback from my email. Plus for anyone reading there is one less click. The basic principle: make a bit of effort at your end to save other's effort (i.e opening the link, reading etc).

More specifically reading this I suspect we could get away without this working for DataPub for now at least for basic usage (for infer we do need it though).

Looking at https://developer.mozilla.org/en-US/docs/Web/API/TransformStream it seems like this is not supported in FireFox, Safari. 

So questions we have:

* Can we get a polyfill for this?
* If not, do we really need TransformStream - could we replace that in the source code with something else that was easier to make web compatible

**Comment by kmanaseryan** [comment]
OK, I guess we have some gap in our communicaton and maybe that's my fault, if yes would be happy to resolve. Let's first clarify why I'm posting here. The porpouse of my comments here is just keep you udpated about my current progress rather than seeking any help, but of course any help will be appreciated. On the other hand I've commented here because this is how it was recommended in the onboarding docs (I think it was in the quize). I really don't want to make someone spend extra time on this and put extra efforts, because of I didn't or don't want to spend time on this, no I just wanted to you keep you guys updated. 

I don't know where you got this, but I've read links and even more found other polyfills too, but I'm already afraid is it safe to post it here. 

Regarding your questons:

 - The issue description asks that too, so it's obvious for me that I'm seeking to find that answer, since didn't find yet I thought it worht posting my updates here, so for other also will be clear, even will save time (not bring extra effort) for later take from here and do further investigation
- If I understood you right, I guess we will endup with our own polyfill, so first let's try to use others.

**Comment by rufuspollock** [comment]
@kmanaseryan more like can we refactor code to not use TransformStream but something else that does not need polyfilling (?)

**Comment by kmanaseryan** [comment]
I think so. I think we can do `Uint8ArrayToStringsTransformer` work outside of `TransformStream`. So just use the initial readable stream came with response and inside the while loop encode the chunks using `TextDecoder`. So if we succeed here, then we can get rid of `TransformStream`. Working on it now, seems promising.

**Comment by mariorodeghiero** [comment]
Sorry, I mentioned the issue number wrong in my commit above.

**Comment by kmanaseryan** [comment]
Blocked by #69

**Comment by kmanaseryan** [comment]
FIXED in #69
